language: python
dist: xenial
sudo: true
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
env:
  - DJANGO="Django==1.8.*"
  - DJANGO="Django==1.9.*"
  - DJANGO="Django==1.10.*"
  - DJANGO="Django==1.11.*"
  - DJANGO="Django==2.0.*"
  - DJANGO="Django==2.1.*"
  - DJANGO="Django==2.2.*"
  - DJANGO="Django==3.0.*"
  - DJANGO="Django==3.1.*"
install:
  - pip install PLY
  - pip install -U $DJANGO
  - pip install -e .
script: python test_project/manage.py test core.tests
notifications:
  slack:
    rooms:
      secure: c/JptnZiplAEh/NJiyj/Wbznv6ufxV2FRN8UD/F4AisRFg/GZGmOc/tiR5+31hOVw++QmUpcfJuriLNeeCDSkPkUu2tEWGKoq1/roY+f/TvVJid/qNgEzLrjGfBFv7CHo7a9fgXukf6+7xr+smomrzxN7MgETpINZl5WxQcHode5YWd/zPsRk+rs2FJ0lkTGM9Vr9H9M4nMgigNrPFOdd4jar37OWoTCApFJ2DGwuxLKOoBkx7iHT4T6wIUhhew9q2Tbh6Cv15wumWxYMmDMNCL0Uy46PV2PFbjLRXplaP+PSkDQ1jHMZvXmpJELTi97QVT9z8LqF8OwDxf5cC2VzKIFE1NdAeaxTHDNHNUTcJENHPc0Svra9AiRnneCcpk94czkNsaeZrECwvFDQYiEg0vBTFLZfmrjKuy7Wmv8YaZdNoYa/ZHx3+cjXPtgHx4cVtxn2GB/layVs8w+2KZi6HUFopo4bdDr5Oj88QipYmN47DG+fecWQkOPu9CLILK7cZksFUu53zl+58i722Eh1Inmei2o5Mru09qodjH5cZ/lo66Ic0UhjFrXFv6xRlYxBeYfmpmbeJnbHUcRmwjVtHEx+dIPpE0jomEVLxxXLwPUw6x32ZUk3fOs+ViNlNkKo1lEngEtzV1febj/bP1em4I+fVykyiFT8e2jfgcM5s0=
matrix:
  exclude:
    - python: 2.7
      env: DJANGO="Django==2.0.*"
    - python: 2.7
      env: DJANGO="Django==2.1.*"
    - python: 2.7
      env: DJANGO="Django==2.2.*"
    - python: 2.7
      env: DJANGO="Django==3.0.*"
    - python: 3.5
      env: DJANGO="Django==3.0.*"
    - python: 2.7
      env: DJANGO="Django==3.1.*"
    - python: 3.5
      env: DJANGO="Django==3.1.*"
    - python: 3.7
      env: DJANGO="Django==1.11.*"
    - python: 3.8
      env: DJANGO="Django==1.9.*"
    - python: 3.8
      env: DJANGO="Django==1.10.*"
